spring.application.name=SpringVeggieService
spring.datasource.name=veggie
spring.datasource.url=jdbc:postgresql://localhost:5432/demo

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.username=demo
spring.datasource.password=demo

spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false

applicationinsights.connection.string=InstrumentationKey=000000-0000-0000-0000-0000000000
client.superhero.url=http://localhost:8081
